[package]
name = "rust-raytracing"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum_dispatch = "0.3.7"
rand = "0.8.4"
rayon = "1.5.1"
winit = "0.25.0"
pixels = "0.4.0"
